Update ex01.c
I've got a problem during compilation because ft_range function returns a pointer to an array of int :

ex01.c: In function ‘main’:
ex01.c:20:48: error: ordered comparison of pointer with integer zero [-Werror=extra]
  printf("ft_range(0, 3): %d\n", ft_range(0, 3) > 0);
                                                ^
ex01.c: error: ordered comparison of pointer with integer zero [-Werror=extra]
  printf("ft_range(2, 5122): %d\n", ft_range(2, 5122) > 0);
                                                      ^
cc1: all warnings being treated as errors